### PR TITLE
added django 1.10 support

### PR DESCRIPTION
**Pull request by rohitchopra32**

### CODE REVIEW

**Comment by arneb** [comment]
thank you!

**Comment by rohitchopra32** [comment]
thanks for this app.
i am using it in my college project.

**Comment by rohitchopra32** [comment]
can I add some notification features to the app ? Like when a user sends message to another user  then an email will be sent automatically to recipient notifying about the message.

**Comment by arneb** [comment]
> can I add some notification features to the app ? Like when a user sends message to another user then an email will be sent automatically to recipient notifying about the message.

that's already part of the app.

**Pull request merged**
