### PR TITLE
Extends Pull Request #116 to add migrations

### PR DESCRIPTION
**Pull request by urtzai**

### CODE REVIEW

**Comment by urtzai** [comment]
@arneb can you merge this pull request and create a new release to be able to run this app in Django 1.11.x? The issue #112 is also a problem when migrating to Django 1.11 that is designated as a long-term support release, and I think fixing it it's a important step. 

Thank you

**Comment by frankystone** [comment]
Yes, this would help to fix other issues as well ...

**Comment by winstongood** [comment]
Please merge and release a django 1.11 package in pypi. Please.

**Comment by arneb** [comment]
current code in master branch should solve this problem

**Pull request closed without merging**
